### PR TITLE
Updated to latest Theia@next and recreated integrity in yarn.lock file

### PR DESCRIPTION
**Pull request by thegecko**
Signed-off-by: Rob Moran <rob.moran@arm.com>

@simark This PR re-implements the integrity I inadvertently removed previously.
As there has been a newer release of Theia@next, this has also been pulled in.

Feel free to discard this PR in favour of #9 already opened if you feel that is better.

### CODE REVIEW

**Comment by thegecko** [comment]
With the latest yarn installed, I removed the `node_modules` folder and ran yarn.

It updated the `theia@next` references and added in the integrity. This method should minimise any version updates.

**Comment by thegecko** [comment]
@marcdumais-work Do you have approval rights?

cc @benoitf

**Comment by marcdumais-work** [comment]
@thegecko Has you committer paperwork gone through? Are you able to merge?

**Comment by thegecko** [comment]
I am :)

**Pull request merged**
