### PR TITLE
Show variables in memory view

### PR DESCRIPTION
**Pull request by simark**

### CODE REVIEW

**Comment by simark** [comment]
@marechal-p

**Comment by simark** [comment]
fileq5hmnr

**Comment by marcdumais-work** [comment]
NPM production dependencies CQ for this change: http://dev.eclipse.org/ipzilla/show_bug.cgi?id=18886

**Comment by marcdumais-work** [comment]
[CQ #18886](http://dev.eclipse.org/ipzilla/show_bug.cgi?id=18886) is `license_certified`! We can proceed with the review and merge this PR at our convenience.

**Pull request closed without merging**
