### PR TITLE
Use the debug adapter from cdt-gdb-vscode/cdt-gdb-adapter

### PR DESCRIPTION
**Pull request by simark**
This patch swaps the debug adapter we use from code-debug to
cdt-gdb-vscode.  We depend on a Theia-specific build, because the
cdt-gdb-vscode package needs some tweak to be import-able as a node
package (which is preferable, IMO, to downloading in a (post)install
script).

Signed-off-by: Simon Marchi <simon.marchi@ericsson.com>

### CODE REVIEW

**Comment by simark** [comment]
@marechal-p @thegecko 

The `@theia/cdt-gdb-vscode` this patch depends on is at

https://github.com/theia-ide/cdt-gdb-vscode

I tested using a local npm registry (using verdaccio), but using `yarn link` would probably work too.  If you agree with the approach, I can see with @marcdumais-work so we can publish `@theia/cdt-gdb-vscode` to the global npm registry.

**Comment by thegecko** [comment]
Hmm, I'm not sure how I feel about patching adapters specifically for Theia. It introduces overhead to continually maintain a fork (which may fall behind the original without committed support).

I'd also like to see all adapters imported in the same way (whether as node modules, downloaded, git modules or otherwise) to promote consistency.

**Comment by simark** [comment]
Ok.  Since there are no releases of cdt-gdb-vscode, where should we host it?

**Comment by simark** [comment]
Ok, I've built the adapter and hosted it in the https://github.com/theia-ide/cdt-gdb-vscode repo (I find it preferable to have it under the `theia-ide` organization rather than under a personal account).  I have updated the patch to make use of it.

**Comment by marcdumais-work** [comment]
> Ok, I've built the adapter and hosted it in the https://github.com/theia-ide/cdt-gdb-vscode repo (I find it preferable to have it under the `theia-ide` organization rather than under a personal account). I have updated the patch to make use of it.

If we eventually use Travis CI in this repo, I think the adapter download during CI will then be subject to the GitHub API rate limit, like we have for ripgrep in the main repo: https://github.com/theia-ide/theia/issues/3787 
I guess we could probably use something else than Travis. Thoughts?

**Comment by thegecko** [comment]
You may be able to add a GH token to avoid limits. Other CI systems allow you to cache downloads which don't change, too (e.g. CircleCI).

**Pull request merged**
