### PR TITLE
Initial layout and C/C++ debugging

### PR DESCRIPTION
**Pull request by marechal-p**

### CODE REVIEW

**Comment by thegecko** [comment]
Should the `extensions` folder be `packages` to match theia?

**Comment by marcdumais-work** [comment]
This PR (except for the mono-repo setup) was already reviewed in repo ```theia-ide/theia```. See https://github.com/theia-ide/theia/pull/2989

**Comment by marechal-p** [comment]
@eclipsewebmaster I cannot merge after approval, is there anything I should do?

**Comment by thegecko** [comment]
👏

**Pull request merged**
